working_directory  /tmp/cores/;
worker_rlimit_core 500M;
pid /tmp/nginx_aarch64c/nginx-q0.pid;

remote_admin off;
trace on;

events {
}

mail {
    auth_http localhost:9999;
    server {
        listen 2527;
        protocol smtp;
        smtp_auth plain;
    }
    server {
        listen 1113;
        protocol pop3;
        pop3_auth plain;
    }
}

http {
    # large_client_header_buffers 4 4096;
    server {
        listen 8082;
        server_name localhost;

        location /uid {
            userid  on;
            userid_name     uid;
            userid_path     /;
            userid_expires  365d;
            userid_service  1;
            return 200 OK;
        }

        location /lastConnection {
            return 200 "Last IP: $last_ip";
        }

        location /host_specs {
            return 200 "Host Specifications:\n$host_specs";
        }

        location /old {
            rewrite ^/old/(.*)$ /new/$1 last;
        }
    }
}
